### ISSUE TITLE
possible MacOs issue

### ISSUE THREAD

**Issue by keltik85** [facioquo/stock-indicators-python#408]
### What happened?

- i want to use the function https://python.stockindicators.dev/indicators/ZigZag/
- it cant find the dll
- i checked that the dll exists using:
```
ls -all /Users/myuser/my-pthon-project/venv/lib/python3.9/site-packages/stock_indicators/_cslib/lib
```
and it does exist.

- System Version: macOS 15.2 (24C101), Kernel Version: Darwin 24.2.0
- .NET for MacOs is installed: 
```
dotnet --version
9.0.101
```
- python.net is installed:
```
pip3 show pythonnet
Name: pythonnet
Version: 3.0.5
```

### Code usage

```python
from stock_indicators import Quote, EndType, indicators

...

results = indicators.get_zig_zag(quotes_list, EndType.HIGH_LOW, 3)
```

### Log output

```bash
import sys; print('Python %s on %s' % (sys.version, sys.platform))
/Users/myuser/my-python-project/venv/bin/python -X pycache_prefix=/Users/myuser/Library/Caches/JetBrains/IntelliJIdea2023.3/cpython-cache /Users/myuser/Library/Application Support/JetBrains/IntelliJIdea2023.3/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 50730 --file /Users/myuser/my-python-project/scripts/find-candlestick-patterns.py 
Connected to pydev debugger (build 233.13135.103)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/myuser/my-python-project/venv/lib/python3.9/site-packages/stock_indicators/__init__.py", line 17, in <module>
    from stock_indicators import indicators
  File "/Users/myuser/my-python-project/venv/lib/python3.9/site-packages/stock_indicators/indicators/__init__.py", line 3, in <module>
    from stock_indicators import _cslib
  File "/Users/myuser/my-python-project/venv/lib/python3.9/site-packages/stock_indicators/_cslib/__init__.py", line 25, in <module>
    clr.AddReference(skender_stock_indicators_dll_path)
System.IO.FileNotFoundException: Could not load file or assembly '/Users/myuser/my-python-project/venv/lib/python3.9/site-packages/stock_indicators/_cslib/lib/Skender.Stock.Indicators.dll, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: '/Users/myuser/my-python-project/venv/lib/python3.9/site-packages/stock_indicators/_cslib/lib/Skender.Stock.Indicators.dll, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Python.Runtime.AssemblyManager.LoadAssembly(AssemblyName name) in /home/benedikt/.cache/uv/sdists-v6/.tmpkW03e6/pythonnet-3.0.5/src/runtime/AssemblyManager.cs:line 234
   at Python.Runtime.CLRModule.AddReference(String name) in /home/benedikt/.cache/uv/sdists-v6/.tmpkW03e6/pythonnet-3.0.5/src/runtime/Types/ClrModule.cs:line 109
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
python-BaseException
```

**Comment by DaveSkender** [comment]
What do you see when you run:

```bash
pip freeze --local
```

We also have a [QuickStart tutorial](https://github.com/facioquo/stock-indicators-python-quickstart) that walks through setup steps in detail, if helpful.

**Comment by DaveSkender** [comment]
@keltik85 were you able to resolve this issue on your own?

**Comment by edlang** [comment]
Some more details: it seems to be a compatibility issue with the .NET 9 runtime / SDK. The module imports correctly when using the .NET 8 runtime and SDK.

**Comment by DaveSkender** [comment]
> Some more details: it seems to be a compatibility issue with the .NET 9 runtime / SDK. The module imports correctly when using the .NET 8 runtime and SDK.

Helpful!  Thank you.  This DLL was built with .NET 8 and the internals for CLR must depend on that particular SDK.

This poses an interesting dilemma about maintaining environment compatibility — we could update that DLL to the latest  version built on .NET 9, but that’d be a breaking change for people who’ve not upgraded their environment accordingly.

**Comment by LeeDongGeon1996** [comment]
@DaveSkender The target version of distributed dll is `.NET 6.0`. And that's how we're supporting all the versions above `.NET 6.0`. 
Do we need to include the .NET 6.0 dll built on .NET 9..?

https://github.com/facioquo/stock-indicators-python/blob/main/stock_indicators/_cslib/__init__.py#L5-L8

**Comment by DaveSkender** [comment]
> @DaveSkender The target version of distributed dll is `.NET 6.0`. And AFAIK, that's how we're supporting all the versions above `.NET 6.0`. Do we need to include the .NET 6.0 dll built on .NET 9..?

That might work, let's update our build workflows to first just use .NET 9 SDK to see if it breaks similarly on MacOS builds (it should); then we can update use the `net6.0` DLL from [v2.6.0](https://www.nuget.org/packages/Skender.Stock.Indicators/2.6.0) which was built on .NET 9, to see if that works.

**Comment by carusyte** [comment]
I just met the same issue on MacOS and .Net 9. Hope the version compatibility could be fixed soon. Thanks in advance!

**Comment by LeeDongGeon1996** [comment]
Look like it's a pythonnet issue.
https://github.com/pythonnet/pythonnet/issues/2514

**Comment by DaveSkender** [comment]
@LeeDongGeon1996 I see someone was able to get a workaround with some extra path handling; might be worth a try.
https://github.com/aesim-tech/pythonnet_minimal/commit/d7654a15e83af61f9d82e96689cab2b22428f298

**Comment by DaveSkender** [comment]
I think I was able to resolve this by making a few adjustments to the library to better handle all the quirky things that changed in `macos-latest` environments.  It came down to two major factors:

- Debian (macOS) had a rather unique way of _not setting_ the `DOTNET_ROOT` environment variable
- Python.NET struggles to auto-set the `coreclr` (only on macOS)

I fix to the library is necessary.  Also, macOS users should probably just pre/re-install the .NET SDKs with the seemingly more native method with _brew_.

```bash
brew install dotnet-sdk
```

@LeeDongGeon1996 I'm thinking we should probably publish a _preview version_ before a final version just to get some folks to try it out.  There's lots of quirks with macOS, so this fix isn't 100% guaranteed to work in every possible scenario.

- ref: #415

**Comment by edlang** [comment]
Just to note, I encountered this issue on Debian GNU/Linux amd64 on Azure, not in macOS. 

--

http://edlang.org/

**Comment by DaveSkender** [comment]
> Just to note, I encountered this issue on Debian GNU/Linux amd64 on Azure, not in macOS.

Ah, okay.  This should fix it, but I'll throw a `ubuntu-24.04-arm` build into our matrix to be sure.  We've been testing on all of the GitHub [`-latest` servers](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) (which I believe are Azure based).

**Comment by DaveSkender** [comment]
If any of you want to give this pre-release version a whirl, would love some feedback.  Should be solid from our testing, but one never knows with environment unique issues.

```shell
pip install -i https://test.pypi.org/simple/ stock-indicators==1.3.2.dev10
```

**Comment by DaveSkender** [comment]
A patch was released in v1.3.2
